job:
  runModel:
    parameters:
      reporting_date: "2021-11-30"
      n_years: 10

    inputs:
      retail_rating_master_scale: "inputs/retail_rating_master_scale.csv"
      retail_transition_matrix: "inputs/retail_transition_matrix.csv"
      gcc_monthly_scenarios: "outputs/gcc_monthly_scenarios.csv"
      gcc_distribution_definition: "outputs/gcc_distribution_definition.csv"
      gcc_macroeconomic_model_coefficients: "inputs/gcc_macroeconomic_model_coefficients.csv"

    outputs:
      gcc_retail_pd_term_structures: "outputs/gcc_retail_pd_term_structures.csv"