
job:
  runModel:
    parameters:

    inputs:
      investment_income: "inputs/ppnr/investment_income.csv"
      fees_and_commissions_income: "inputs/ppnr/fees_and_commissions_income.csv"
      balance_forecast: "outputs/balance_forecast.csv"

    outputs:
      non_interest_income: "outputs/non_interest_income.csv"
