
job:
  runModel:
    parameters:
      first_forecast_month: "2021-01-01"
      last_forecast_month: "2021-12-01"

    inputs:
      economic_scenario: "inputs/economic_scenario.csv"
      mortgage_book_t0: "inputs/mortgage_book_t0_schema.csv"

    outputs:
      pd_forecast: "outputs/pd_forecast.csv"
