
job:
  runModel:
    parameters:
      expected_base_rate: 1
      expected_employee_cost_change: 0.0

    inputs:
      non_interest_income: "outputs/non_interest_income.csv"
      operating_costs: "outputs/operating_costs.csv"
      net_interest_income: "outputs/net_interest_income.csv"

    outputs:
      operating_profit: "outputs/operating_profit.csv"
      total_income: "outputs/total_income.csv"
