
job:
  runModel:
    parameters:
      expected_base_rate: 1
      expected_employee_cost_change: 0.0

    inputs:
      interest_earned_assets: "inputs/average_interest_earned_on_assets.csv"
      interest_paid_assets: "inputs/average_interest_paid_on_assets.csv"

    outputs:
      net_interest_margin: "outputs/net_interest_margin.csv"
