
job:
  runModel:
    parameters:
      expected_base_rate: 1
      expected_employee_cost_change: 0.0

    inputs:
      business_support_costs: "inputs/business_support_costs.csv"
      processing_costs: "inputs/processing_costs.csv"
      sales_and_marketing_costs: "inputs/sales_and_marketing_costs.csv"
      corporate_centre_costs: "inputs/corporate_centre_costs.csv"

    outputs:
      operating_costs: "outputs/operating_costs.csv"
