
job:
  runModel:
    parameters:
      first_forecast_month: "2021-01-01"
      last_forecast_month: "2021-12-01"

    inputs:
      lgd_model_parameters: "inputs/impairment/lgd_model_parameters.csv"
      ead_forecast: "outputs/impairment/ead_forecast.csv"

    outputs:
      lgd_forecast: "outputs/impairment/lgd_forecast.csv"
