
job:
  runModel:
    parameters:
      first_forecast_month: "2021-01-01"
      last_forecast_month: "2021-12-01"

    inputs:
      ead_model_parameters: "inputs/impairment/ead_model_parameters.csv"
      balance_forecast: "inputs/impairment/balance_forecast.csv"
      mortgage_book_t0: "inputs/impairment/mortgage_book_t0.csv"

    outputs:
      ead_forecast: "outputs/impairment/ead_forecast.csv"
